using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class InternalLinkType : Object
        {
            /// <summary>
            /// The link is a link to a voice chat. Call searchPublicChat with the given chat username, and then joinGoupCall with the given invite hash to process the link
            /// </summary>
            public class InternalLinkTypeVoiceChat : InternalLinkType
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "internalLinkTypeVoiceChat";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Username of the chat with the voice chat
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("chat_username")]
                public string ChatUsername { get; set; }

                /// <summary>
                /// If non-empty, invite hash to be used to join the voice chat without being muted by administrators
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("invite_hash")]
                public string InviteHash { get; set; }
            }
        }
    }
}